### ISSUE TITLE
Workshops page should have curriculum filter even if lesson program is identified

### ISSUE THREAD

**Issue by maneesha** [carpentries/carpentries-hugo-theme#36]
As completed in https://github.com/carpentries/carpentries-hugo-theme/issues/8, the workshops page should not have the lessons filter if the lesson program is identified in the yaml frontmatter.

However, we should still have the curriculum filter.

**Comment by regisphilibert** [comment]
I don't think we ever had curriculum on lessons, they're not mentioned in the data file.

```yaml
 -  program: DC
    name: Foundations of Astronomical Data Science
    description: An introduction to core concepts necessary to efficiently study the ever-growing datasets developed in modern astronomy. This curriculum is aimed at researchers and others, who want to perform database operations (SQL queries, joins, filtering) and to create publication-quality visualisations with astronomy data.
    tool: Python
    skill: Data visualisation; Accessing data; Programming
    language: English
    domain: Astronomy
    url: https://datacarpentry.org/astronomy-python/
  ```
